# Generated by Django 5.0.3 on 2024-03-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40, verbose_name='Username')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('password', models.CharField(max_length=16, verbose_name='Contraseña')),
            ],
        ),
    ]
