"""empty message

Revision ID: 3f6610fe4e74
Revises: 
Create Date: 2024-04-20 23:35:09.800375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f6610fe4e74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('plan', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=False)
    op.alter_column('user', '_password_hash',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', '_password_hash',
               existing_type=sa.String(length=16),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('plan', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=False)
    op.drop_table('user_recipe')
    # ### end Alembic commands ###
