# Generated by Django 3.2 on 2024-04-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NutriCUT', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
